oauth_key: "your-slack-oauth-key"
ssids:
  - "iCapps,@icapps,:icapps:"
  - "iCapps Corda,@Corda,:corda:"
  - "Farmboy Co-working,@icapps Gent,:gent:"
  - "CRONOS Wifi,@icapps Mechelen ,:mechelen:"
  - "CRONOS Guest,@Cronos,:cronos:"
unknown:
  - "Working in an unknown environment,:zap:"